---
- name: Add multiple users
  hosts: demo
  become: yes
  vars:
    user_list:
      - name: john
        shell: /bin/bash
      - name: jenelia
        shell: /bin/bash
      - name: christoper
        shell: /bin/bash

  tasks:
    - name: Create users from user_list
      user:
        name: "{{ item.name }}"
        shell: "{{ item.shell }}"
        state: present
        create_home: yes
      loop: "{{ user_list }}"


