---
- name: the gather facts demo
  hosts: demo
  become: yes
  gather_facts: yes
  tasks:
  - name: the distribution and ditstribution version
    debug:
        msg: "the distribution and distribution version is {{ ansible_distribution }} {{ ansible_distribution_version }}"
  - name: the address 
    debug: 
        msg: "the address and addresses is {{ ansible_default_ipv4.address }} {{ ansible_all_ipv4_addresses }}"
  - name: cpu information
    debug:
        msg: "the cpu detail is {{ ansible_processor_cores }}"
  - name: the real mb
    debug:
        msg: "the real mb is {{ ansible_memory_mb.real.total }}"
  - name: disk space
    debug:
        msg: "disk size is {{ ansible_mounts[0].size_total | human_readable }}"
  - name: the memory
    debug:
        msg: "the memory is {{ ansible_memtotal_mb }}"
