---
- name: gather facts demo
  hosts: demo
  become: yes
  tasks:
     
    - name: Print OS type and version
      debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_os_family }})"

    - name: Print IP address
      debug:
        msg: "IP Address: {{ ansible_default_ipv4.address }}"

    - name: Print hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Print CPU info
      debug:
        msg: "CPU: {{ ansible_processor_cores }} cores"

    - name: Print memory info
      debug:
        msg: "Memory: {{ ansible_memory_mb.real.total }} MB"

    - name: Print disk space info (root partition)
      debug:
        msg: "Disk Size (root): {{ ansible_mounts[0].size_total | human_readable }}"

    - name: Print network interfaces
      debug:
        var: ansible_interfaces

  handlers:
    - name: Restart Apache
      service:
        name: "{{ web_service }}"
        state: restarted

