#SPDX-License-Identifier: MIT-0
---
# tasks file for apache
#

- name: Install Apache2
  ansible.builtin.apt:
    name: apache2
    state: present
  notify: restart apache

- name: Ensure Apache is running
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true


